### ISSUE TITLE
Missing success message

### ISSUE THREAD

**Issue by GavinAndersonGuvnor** [kc9wwh/FileVaultEnableAdminAccount#1]
Hi Joshua,

Many thanks for this excellent script. Just noted that the 'SUCCESS_MESSAGE' you set near the top never gets called later on when the process is actually successful, not sure if you want to add that in.

Thanks again!

**Comment by kc9wwh** [comment]
Ha! Thanks @GavinAndersonGuvnor for pointing that out. The initial idea was to not have a message displayed on success, so I will get that variable removed.

Thanks again!

**Comment by kc9wwh** [comment]
Resolved w/ commit 341b499
