### ISSUE TITLE
Modify to allow script to run during encryption

### ISSUE THREAD

**Issue by jelockwood** [kc9wwh/FileVaultEnableAdminAccount#4]
As far as I can see from my use of it, the script will only run successfully if the FileVault2 encryption process has finished - that is it will report an error if you try it whilst encryption is in progress.

Also as far as I can see this maybe an unnecessary restriction. If indeed _technically_ it is possible to run the commands used in the script whilst encryption is still in progress I would request that the script be modified to allow this. This would allow this script to run sooner and allow issuing the laptop to the user sooner. As things stand either we would have to educate the user on what they need to do when the script runs and also they would only be able to do this if their account is an admin level account, or we would as we currently do have to keep the laptop until encryption is fully complete so we can then ensure this script gets run. As FileVault2 encryption on APFS takes much, _much_ longer than on HFS+ this adds quite a lot of delay.

**Comment by kc9wwh** [comment]
Hey @jelockwood - in past experience we've seen issues when trying to do this before the device is encrypted and technically we are not supposed to be able to FV enable users until encryption is complete.
