### ISSUE TITLE
Error making "ADMIN_USER" FileVault Enabled

### ISSUE THREAD

**Issue by derekritchison** [kc9wwh/FileVaultEnableAdminAccount#5]
Hey there! I was directed to this script yesterday by a Jamf customer support agent as I've been trying to address a number of machines where our Jamf-created local admin is not enabled for secure token.

I've configured everything per instructions here and in the additional YouTube video, but I am still getting the following error --- on multiple machines and on multiple OS versions (12 and 14). Is there any way we can dig deeper than what I'm seeing in the attached screencap and learn why it is failing?

<img width="1253" alt="enable_secure_token" src="https://user-images.githubusercontent.com/28872338/63054972-b9eb7380-be99-11e9-8d13-a2e136ae6cd7.PNG">

**Comment by jelockwood** [comment]
I am using the same script and same 1.7.2 version successfully. However the order of things may be different and may help you.

We build Macs, currently this is done via DeployStudio and during this process a local admin account is created which does have a secure token. We enrol currently via the QuickAdd.pkg which then triggers via Jamf post enrolment policies FileVault2 encryption and this uses the aforementioned local admin account. There is also a script that performs LAPS which randomises and stores in Jamf the local admin password.

The important thing I found was to ensure both the FileVault2 encryption and LAPS had completed successfully before running the FileVaultEnableAdminAccount script. This is achieved via smart groups.

You might ask why I still use the FileVaultEnableAdminAccount script if the local admin account is already created and already has a secure token? The sad reality is that the Jamf Management account which gets created during enrolment does _not_ have a secure token at that point. We therefore use the script to put up a dialog which the local admin account sees and allows adding a secure token to the Jamf Management account.

This then allows later the Jamf Management account to replace FileVault2 recovery keys periodically. After all the above is complete we then create a local user account for the intended user.

This is working for Mojave and High Sierra.

I am guessing you may have a slightly process which involves _first_ creating the local user account and then after enrolment creating the local admin and Jamf Management accounts. It could be the need to complete FileVault2 encryption first might still apply but you would likely need to create secure tokens for both the local admin and Jamf Management accounts.

**Comment by derekritchison** [comment]
Hey there! Thanks for such a detailed response! As far as our enrollment process, well, it's fairly straightforward. Our machines are all (well, mostly) DEP. We fire them up, and after connecting to WiFi we get the "this machine can be managed by..." enrollment screen. After that we create the local account for the new hire / end user... which, of course, gets the secure token. From here, it's still a little more hands on / manual than I'd prefer (and we're working on that) but basically I trigger the FV2 encryption by logging out and then run a couple other "pre-onboarding" tasks.

At this point I could "easily" enable our Jamf-created admin account for FV2 since I know the local user's first time password (and I _do_ do this for now) but I would much prefer if the user were simply prompted at some point during their first day. (Plus, this would much more easily solve the large "back order" of machines that were never enabled before we caught this bug.)

So, it seems like outside of the DeployStudio imaging we're doing things in the same order --- the Jamf-created admin is created just before the local user/local admin.

**Comment by jelockwood** [comment]
I am not yet using DEP and hence have not tried this script after DEP but I don't believe that and not using Quickadd.pkg should make a difference.

I would advise making sure FileVault has fully completed before allowing this script to run since that seemed to help my setup.

As i am using the same script it does display the dialog and the user - in my case the local admin account has to authorise the generation of a secure token for the Jamf account. It might therefore also be worth targeting that account first.

**Comment by derekritchison** [comment]
Yeah. FV has definitely fully completed. And I'm seeing this on at least three different machines now. Odd...

**Comment by derekritchison** [comment]
And more odd, if I open Terminal and run the standard sysadminctl command:

sysadminctl -adminUser username -adminPassword password -secureTokenOn itsupport -password -

...and then enter my password, it works.

**Comment by kc9wwh** [comment]
Hey @derekritchison - reviewing the thread here and especially with your finding yesterday, my guess is that something is wrong with the encrypted strings. This can be very tricky at times especially with special characters in passwords. 

When you generated the encryptedString, did you use the bash or python method? If you used the bash method, can we try using python to generate the encryptedStrings? [Here is a quick video on this.](https://www.youtube.com/watch?v=KoBGMPTU9Io)

Let me know how it goes.

**Comment by derekritchison** [comment]
Interesting. And yes, I used bash. Let me try and generate those strings using the Python method next chance I get!

**Comment by derekritchison** [comment]
I encrypted the password via the Python method, but got the same result --- "success" in the Self Service button but a non-descriptive error in the Jamf policy logs. To be certain, I am using the values generated when I encrypt the username in PARAM 4 (ADMIN_USER_ENCRYPTED) and PARAM 6 (SALT) and PARAM 7 (PASSPHRASE), and I am using the single value generated when I encrypt the password in PARAM 5 (ADMIN_PASS_ENCRYPTED). Maybe I am simply missing a simple step here?

**Comment by derekritchison** [comment]
Ah. I _think_ I found what I missed. They have to use the same SALT and PASSPHRASE (duh...) and I'm pretty sure mine are not.

**Comment by kc9wwh** [comment]
Yes @derekritchison the `ADMIN_USER_ENCRYPTED` and `ADMIN_PASS_ENCRYPTED` do require the same `SALT` and `PASSPHRASE` values to decrypt them. To do this, you need to modify the function to utilize the same `SALT` and `PASSPHRASE` when encrypting the password if you do the username first.

**Comment by derekritchison** [comment]
Done. Working. I'm a dummy... but Jamf is sorta helping me appear less so!

**Comment by kc9wwh** [comment]
No problem! We all learn as we go and this is a little different use of encryptedStrings. ¯\_(ツ)_/¯

Glad you got it working :)
