### ISSUE TITLE
Incompatible with Big Sur / 11.0.1 

### ISSUE THREAD

**Issue by erishiamu** [kc9wwh/FileVaultEnableAdminAccount#6]
This currently does not function on BigSur. 

Initial issue during execution @ line 140
`# Check the OS version.

Big Sur is 11.0.#, validation will fail due to being below required version. Similar logic is used elsewhere in the script and fails as well.

**Comment by jelockwood** [comment]
@erishiamu 
@kc9wwh 
This ticket has been closed but I do not see a fix implemented. Is there a fix?
